### ISSUE TITLE
ER_ACCESS_DENIED_ERROR

### ISSUE THREAD

**Issue by cansoysal** [michalkow/node-mysql-model#9]
Hello,
I'm having connection problem. Same connection options works with Felix's Mysql. However I can't make it work with your module. Any suggestions?

Node Version: v6.5.0
MYSQL Version: Ver 14.14

Thank you.

**Comment by avipersin** [comment]
Finally fixed this issue!

Basically if you download the module using "npm install mysql-module" you will notice it ships with it's own node_modules directory. Inside the node_modules directory is the "mysql" module. 

```
var mysql = require("mysql");  // mysql-model.js (line 3)
```
Is actually importing the local mysql module from /node_modules/mysql-model/mysql which is from who knows when.

After deleting /node_modules/mysql-model/mysql/ the import is now referencing the updated mysql library in /node_modules/mysql and everything works properly!

I also recommend changing mysql-model.js (line 7) to:
```
var connection = mysql.createConnection(options);
```
So that you don't run into errors when the connection times out.

**Comment by michalkow** [comment]
I moved the project to a new repo: https://github.com/michalkow/node-mysql-backbone
I separated Model and Collection code from node-mysql library.
